//
//  AppText.swift
//  Reynard
//
//  Created by Codex on 8/7/26.
//

import Foundation

enum AppText {
    static var locale: Locale {
        return Prefs.BrowsingSettings.language == .chinese
        ? Locale(identifier: "zh_CN")
        : Locale(identifier: "en_US")
    }

    static func text(_ english: String) -> String {
        guard Prefs.BrowsingSettings.language == .chinese else {
            return english
        }
        return simplifiedChinese[english] ?? english
    }

    static func onOff(_ value: Bool) -> String {
        return text(value ? "On" : "Off")
    }

    static func tabCount(_ count: Int) -> String {
        if Prefs.BrowsingSettings.language == .chinese {
            return "\(count) 个标签页"
        }
        return "\(count) \(count == 1 ? "Tab" : "Tabs")"
    }

    static func format(_ englishFormat: String, _ arguments: CVarArg...) -> String {
        return String(format: text(englishFormat), locale: locale, arguments: arguments)
    }

    static func closingTabCount(_ count: Int) -> String {
        if Prefs.BrowsingSettings.language == .chinese {
            return "这会关闭你的 \(count) 个标签页。"
        }
        return "This will close your \(count) \(count == 1 ? "tab" : "tabs")."
    }

    static func addressCount(_ count: Int) -> String {
        if Prefs.BrowsingSettings.language == .chinese {
            return "\(count) 个地址"
        }
        return "\(count) \(count == 1 ? "address" : "addresses")"
    }

    private static let simplifiedChinese: [String: String] = [
        "About": "关于",
        "Add Bookmark": "添加书签",
        "Add": "添加",
        "Add-ons": "扩展",
        "Add to Favorites": "添加到收藏",
        "Add Website": "添加网站",
        "Add Website...": "添加网站…",
        "Additional Options": "其它选项",
        "Address": "地址",
        "Address Bar": "地址栏",
        "After you close a tab, Reynard won't remember any of your browsing history or cookies. However, downloads and new bookmarks will be saved.": "关闭标签页后，Reynard 不会记录你的浏览历史或 Cookie，但下载的文件和新建的书签仍会保留。",
        "All Website": "所有网站",
        "All history": "全部历史记录",
        "Appearance": "外观",
        "Autoplay": "自动播放",
        "Blank Page": "空白页",
        "Bookmarks": "书签",
        "Bottom": "底部",
        "Browsing": "浏览",
        "Cancel": "取消",
        "Cancel Download": "取消下载",
        "Cancel Download?": "要取消下载吗？",
        "Choose what to see when you open Reynard.": "选择打开 Reynard 时显示的内容。",
        "Choose what to show on the homepage.": "选择主页上显示的内容。",
        "Clear All": "全部清除",
        "Clear Browsing Data": "清除浏览数据",
        "Clear Downloads": "清除下载记录",
        "Clear Downloads History": "清除下载历史记录",
        "Clear History": "清除历史记录",
        "Clear Timeframe": "清除时间范围",
        "Clearing downloads history does not delete files in your Downloads folder.": "清除下载历史记录不会删除“下载”文件夹中的文件。",
        "Close All Tabs": "关闭所有标签页",
        "Compatibility": "兼容性",
        "Copy": "复制",
        "Copy Link": "复制链接",
        "Custom URL": "自定义 URL",
        "Day": "日间",
        "Date Added": "添加日期",
        "Default": "默认",
        "Delete": "删除",
        "Delete Bookmark": "删除书签",
        "Delete Folder": "删除文件夹",
        "Deleted": "已删除",
        "Do you want to stop downloading %@?": "要停止下载“%@”吗？",
        "Done": "完成",
        "Downloads": "下载",
        "Engine Version": "引擎版本",
        "Edit Bookmark": "编辑书签",
        "Edit Bookmarks": "编辑书签",
        "Edit": "编辑",
        "Favorites": "收藏",
        "Files you download appear here": "下载的文件会显示在这里",
        "Folders": "文件夹",
        "Frequently Visited": "经常访问",
        "General": "通用",
        "History": "历史记录",
        "Homepage": "主页",
        "If you encounter issues such as sign-in failures, human verification challenges, or other incorrect site behavior, adding the site's URL to this user agent override list may help resolve the problem.": "如果遇到登录失败、人机验证异常或其它网站行为不正确的问题，把该网站 URL 加入用户代理覆盖列表可能有助于解决。",
        "JIT": "JIT",
        "Keep Downloading": "继续下载",
        "Landscape Tab Bar": "横屏标签栏",
        "Language": "语言",
        "Last Tab": "上次标签页",
        "Last hour": "过去一小时",
        "Links": "链接",
        "Location": "位置",
        "Media": "媒体",
        "Name": "名称",
        "New Folder": "新建文件夹",
        "New Tab": "新标签页",
        "Night": "夜间",
        "No Add-ons": "没有扩展",
        "No matching bookmarks": "没有匹配的书签",
        "No matching downloads": "没有匹配的下载记录",
        "No matching history": "没有匹配的历史记录",
        "None": "无",
        "Off": "关闭",
        "On": "开启",
        "Open Downloads Folder": "打开下载文件夹",
        "Open in\nFiles": "在“文件”中\n打开",
        "Open in New Private Tab": "在新无痕标签页中打开",
        "Open in New Tab": "在新标签页中打开",
        "Opening Screen": "启动页面",
        "Page Zoom": "页面缩放",
        "Privacy": "隐私",
        "Private": "无痕浏览",
        "Private Browsing": "无痕浏览",
        "Previous 7 Days": "过去 7 天",
        "Previous 30 Days": "过去 30 天",
        "Reynard won't remember any of your browsing history or cookies. However, downloads and new bookmarks will be saved.": "Reynard 不会记录你的浏览历史或 Cookie，但下载的文件和新建的书签仍会保留。",
        "Reynard Browser": "Reynard 浏览器",
        "Recently Closed Tabs": "最近关闭的标签页",
        "Remove Link": "移除链接",
        "Remove Recently Closed Tab": "从最近关闭中移除",
        "Request Desktop Website On": "请求桌面网站",
        "Request Desktop Website": "切换为电脑版网站",
        "Request Mobile Website": "切换为移动版网站",
        "Search": "搜索",
        "Search Bookmarks": "搜索书签",
        "Search Downloads": "搜索下载记录",
        "Search History": "搜索历史记录",
        "Search Browsing History": "搜索浏览历史",
        "Search Engine": "搜索引擎",
        "Search Opened Tabs": "搜索已打开标签页",
        "Search Suggestion Provider": "搜索建议提供方",
        "Search Suggestions": "搜索建议",
        "Save to Photos": "保存到照片",
        "Save": "保存",
        "Settings": "设置",
        "Show Full Website Address": "显示完整网站地址",
        "Show All": "显示全部",
        "Show Image Previews": "显示图片预览",
        "Show in Private Browsing": "在无痕浏览中显示",
        "Show Link Previews": "显示链接预览",
        "Show Less": "收起",
        "Show on Homepage": "在主页显示",
        "Show on New Tab": "在新标签页显示",
        "Show Search Suggestions": "显示搜索建议",
        "Site Permissions": "网站权限",
        "Specific Site Settings": "特定网站设置",
        "Share Image": "分享图片",
        "Share Link": "分享链接",
        "Share": "分享",
        "Show Folders on Top": "文件夹置顶",
        "Support The Project": "支持项目",
        "Sort By": "排序方式",
        "System": "跟随系统",
        "Tabs": "标签页",
        "The browser will use a desktop Firefox user agent for navigating the web.": "浏览器会使用桌面版 Firefox 用户代理访问网页。",
        "To maximize compatibility, the browser will use the Firefox for Android user agent for navigating the web. As a result, websites may identify your device as an Android device.": "为了提高兼容性，浏览器会使用 Android 版 Firefox 用户代理访问网页。因此，网站可能会把你的设备识别为 Android 设备。",
        "Top": "顶部",
        "Title": "标题",
        "Today": "今天",
        "Today and yesterday": "今天和昨天",
        "Untitled": "无标题",
        "Unknown size": "大小未知",
        "Update Available": "有可用更新",
        "Use Android User Agent": "使用 Android 用户代理",
        "User Agent Overrides": "用户代理覆盖",
        "URL": "网址",
        "View Source Code": "查看源代码",
        "Website Settings": "网站设置",
        "Websites that support multiple languages will prefer the selected language. Open pages may need to be reloaded.": "支持多语言的网站会优先使用所选语言。已打开的页面可能需要重新加载。",
        "When long-pressing images": "长按图片时",
        "When long-pressing links": "长按链接时",
        "Yesterday": "昨天",
        "Your browsing history appears here": "浏览历史记录会显示在这里",
        "Allow": "允许",
        "Allow Audio and Video": "允许音频和视频",
        "Allowed Sites": "允许的网站",
        "Allowed on %@": "允许于 %@",
        "Ask": "每次询问",
        "Block Audio and Video": "阻止音频和视频",
        "Block Audio only": "仅阻止音频",
        "Browsing History": "浏览历史记录",
        "Cached Images and Files": "缓存的图像和文件",
        "Camera": "相机",
        "Changed Sites": "已更改的网站",
        "Changed on %@": "更改于 %@",
        "Clear": "清除",
        "Cookies and Site Data": "Cookie 和网站数据",
        "Cross-site Cookies": "跨站 Cookie",
        "Default Behavior": "默认行为",
        "Denied Sites": "拒绝的网站",
        "Denied on %@": "拒绝于 %@",
        "Deny": "拒绝",
        "Device Apps and Services": "设备上的 App 与服务",
        "Downloaded Files": "已下载的文件",
        "Downloads History": "下载历史记录",
        "Failed to clear browsing data": "清除浏览数据失败",
        "Frees up storage space": "释放存储空间",
        "Local Network Devices": "本地网络设备",
        "Microphone": "麦克风",
        "No Sites Added": "尚未添加网站",
        "OK": "确定",
        "Open Settings": "打开设置",
        "Opened Tabs": "已打开的标签页",
        "Permissions": "权限",
        "Persistent Storage": "持久存储",
        "Reset Page Zoom Settings": "重置页面缩放设置",
        "Reset Permissions for all Sites": "重置所有网站的权限",
        "This action will clear all of your browsing data. It cannot be undone.": "此操作会清除全部浏览数据，且无法撤销。",
        "This action will reset permissions for all sites. It cannot be undone.": "此操作会重置所有网站的权限，且无法撤销。",
        "You'll be logged out of most sites": "你将退出大多数网站的登录",
        "Zoom Level": "缩放级别",
        "Navigations to these websites will use the browser's compatibility user agent. Depending on your Request Desktop Website setting, these websites may identify your device as either an Android device or a desktop Linux device.": "访问这些网站时将使用浏览器的兼容性用户代理。根据“请求桌面网站”设置，网站可能会将设备识别为 Android 设备或桌面 Linux 设备。",
        "Could not retrieve the download URL.": "无法获取下载地址。",
        "Download Failed": "下载失败",
        "Downloading Update": "正在下载更新",
        "Enable JIT": "启用 JIT",
        "Enable JIT to improve performance and ensure websites work properly.": "启用 JIT 可提升性能，并确保网站正常运行。",
        "Import Failed": "导入失败",
        "Import Pairing File...": "导入配对文件…",
        "Invalid Search URL": "搜索网址无效",
        "Enter a valid http(s) URL containing %s where the search query should go.": "请输入包含 %s 的有效 http(s) 网址，%s 将替换为搜索内容。",
        "Install the TrollStore version of Reynard to enable JIT automatically for improved performance and to ensure websites work properly.": "安装 TrollStore 版 Reynard 可自动启用 JIT，以提升性能并确保网站正常运行。",
        "JIT is not supported on the OS version you are using.": "当前系统版本不支持 JIT。",
        "Make sure TrollStore's URL Scheme is enabled.": "请确保 TrollStore 的 URL Scheme 已启用。",
        "No release notes available.": "暂无发行说明。",
        "Preparing JIT": "正在准备 JIT",
        "Restart Required": "需要重新启动",
        "Since this is your first time enabling JIT, Reynard needs to download and mount the Developer Disk Image. This is required for JIT to work properly.": "首次启用 JIT 时，Reynard 需要下载并挂载开发者磁盘映像，这是 JIT 正常运行所必需的。",
        "The app will now close for the JIT setting to take effect.": "应用将立即关闭，以使 JIT 设置生效。",
        "This build does not support in-app updates. Visit the project's Releases page to download the latest version of the app.": "此版本不支持应用内更新。请前往项目的 Releases 页面下载最新版本。",
        "Update Now": "立即更新",
        "Update Unavailable": "无法更新",
        "Version %@": "版本 %@",
        "When the download finishes, choose the app that you used to sideload Reynard in the share sheet to install the update.": "下载完成后，请在分享菜单中选择用于侧载 Reynard 的应用来安装更新。",
        "Number of Items": "项目数量",
        "Number of Rows": "行数",
        "Number of Sites": "网站数量",
        "Show Favorites": "显示收藏",
        "Show Frequently Visited": "显示经常访问",
        "Show Recently Closed Tabs": "显示最近关闭的标签页",
        "Complete Add-on Updates": "完成扩展更新",
        "Discover Add-ons...": "发现扩展…",
        "Install Add-on From File...": "从文件安装扩展…",
        "Installed Add-ons": "已安装的扩展",
        "Installing Add-on...": "正在安装扩展…",
        "Last checked on %@.": "上次检查：%@。",
        "Loading Add-ons...": "正在加载扩展…",
        "Needs permission to update": "需要授权才能更新",
        "No Add-ons Installed": "尚未安装扩展",
        "No updates found.": "未发现更新。",
        "Unsupported": "不受支持",
        "Unsupported Add-ons": "不受支持的扩展",
        "Update All Add-ons": "更新所有扩展",
        "Updating Add-ons...": "正在更新扩展…",
        "Are you sure you want to upload all files? Only do this if you trust the site.": "确定要上传所有文件吗？请仅在信任此网站时继续。",
        "Are you sure you want to upload all files from \"%@\"? Only do this if you trust the site.": "确定要上传“%@”中的所有文件吗？请仅在信任此网站时继续。",
        "Bookmarks, History, and Tabs": "书签、历史记录和标签页",
        "Choose File": "选择文件",
        "Choose Folder": "选择文件夹",
        "Confirm Upload": "确认上传",
        "Do you want to download \"%@\"?": "要下载“%@”吗？",
        "Download": "下载",
        "No": "否",
        "Option": "选项",
        "Photo Library": "照片图库",
        "Search or enter website name": "搜索或输入网站名称",
        "Select Option": "选择选项",
        "Select Options": "选择多个选项",
        "Take Photo": "拍照",
        "Take Photo or Video": "拍照或录像",
        "Take Video": "录像",
        "Upload": "上传",
        "Yes": "是",
        "A new version of Reynard Browser is available. Open Settings to update.": "Reynard 浏览器有新版本可用，请打开设置进行更新。",
        "Buy Me a Coffee": "请我喝杯咖啡",
        "Download Reynard (.tipa)": "下载 Reynard（.tipa）",
        "Hi, I'm Minh, the developer of Reynard. If you find the project useful, sponsoring me helps keep it alive and maintained. Thanks for the support!": "你好，我是 Reynard 的开发者 Minh。如果这个项目对你有帮助，赞助可以支持项目继续维护。感谢你的支持！",
        "Install TrollStore": "安装 TrollStore",
        "Learn More": "了解更多",
        "Not Now": "暂不",
        "Performance Recommendation": "性能建议",
        "Allow %@ to access apps and services on devices connected to your local network?": "允许 %@ 访问本地网络中设备上的 App 和服务吗？",
        "Allow %@ to access other apps and services on this device?": "允许 %@ 访问此设备上的其它 App 和服务吗？",
        "Allow %@ to play DRM-controlled content?": "允许 %@ 播放受 DRM 保护的内容吗？",
        "Allow %@ to send notifications?": "允许 %@ 发送通知吗？",
        "Allow %@ to store data in persistent storage?": "允许 %@ 持久存储数据吗？",
        "Allow %@ to use motion & orientation sensors?": "允许 %@ 使用运动与方向传感器吗？",
        "Allow %@ to use its cookies on %@?": "允许 %@ 在 %@ 上使用其 Cookie 吗？",
        "Allow %@ to use your camera and microphone?": "允许 %@ 使用相机和麦克风吗？",
        "Allow %@ to use your camera?": "允许 %@ 使用相机吗？",
        "Allow %@ to use your location?": "允许 %@ 使用你的位置吗？",
        "Allow %@ to use your microphone?": "允许 %@ 使用麦克风吗？",
        "Reset Permissions for this Site": "重置此网站的权限",
        "Settings for %@": "%@ 的设置",
        "This action will reset permissions for this site. It cannot be undone.": "此操作会重置此网站的权限，且无法撤销。",
        "You may want to block access if it’s not clear why %@ needs this data.": "如果不清楚 %@ 为什么需要这些数据，建议阻止访问。",
        "This extension is blocked for violating Mozilla's policies and has been disabled.": "此扩展违反 Mozilla 政策，已被停用。",
        "This extension isn't supported by this version of Reynard and has been disabled.": "当前版本的 Reynard 不支持此扩展，已将其停用。",
        "Add-on": "扩展",
        "Author": "作者",
        "Details": "详情",
        "Do you want to remove %@?": "要移除“%@”吗？",
        "Enabled": "已启用",
        "Failed to reload add-on": "重新加载扩展失败",
        "Failed to remove add-on": "移除扩展失败",
        "Failed to update permissions": "更新权限失败",
        "Failed to update private browsing access": "更新无痕浏览权限失败",
        "Information": "信息",
        "Last updated": "上次更新",
        "More about this extension": "关于此扩展的更多信息",
        "Optional Data Collection": "可选数据收集",
        "Optional Permissions": "可选权限",
        "Rating": "评分",
        "Remove": "移除",
        "Required Data Collection": "必要的数据收集",
        "Required Permissions": "必要权限",
        "Version": "版本",
        "Zoom Settings": "缩放设置",
    ]
}
